PohybStrava/Controllers/PotravinyDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PohybStrava.Data;
using PohybStrava.Models;

namespace PohybStrava.Controllers
{
    public class PotravinyDatabaseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PotravinyDatabaseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PotravinyDatabase
        public async Task<IActionResult> Index()
        {
              return View(await _context.PotravinyDatabase.ToListAsync());
        }

        // GET: PotravinyDatabase/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PotravinyDatabase == null)
            {
                return NotFound();
            }

            var potravinyDatabase = await _context.PotravinyDatabase
                .FirstOrDefaultAsync(m => m.PotravinaDatabaseId == id);
            if (potravinyDatabase == null)
            {
                return NotFound();
            }

            return View(potravinyDatabase);
        }

        // GET: PotravinyDatabase/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PotravinyDatabase/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PotravinaDatabaseId,Email,PotravinaDatabase,Jednotka,EnergieDatabase")] PotravinyDatabase potravinyDatabase)
        {
            if (ModelState.IsValid)
            {
                _context.Add(potravinyDatabase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(potravinyDatabase);
        }

        // GET: PotravinyDatabase/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PotravinyDatabase == null)
            {
                return NotFound();
            }

            var potravinyDatabase = await _context.PotravinyDatabase.FindAsync(id);
            if (potravinyDatabase == null)
            {
                return NotFound();
            }
            return View(potravinyDatabase);
        }

        // POST: PotravinyDatabase/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PotravinaDatabaseId,Email,PotravinaDatabase,Jednotka,EnergieDatabase")] PotravinyDatabase potravinyDatabase)
        {
            if (id != potravinyDatabase.PotravinaDatabaseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(potravinyDatabase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PotravinyDatabaseExists(potravinyDatabase.PotravinaDatabaseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(potravinyDatabase);
        }

        // GET: PotravinyDatabase/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PotravinyDatabase == null)
            {
                return NotFound();
            }

            var potravinyDatabase = await _context.PotravinyDatabase
                .FirstOrDefaultAsync(m => m.PotravinaDatabaseId == id);
            if (potravinyDatabase == null)
            {
                return NotFound();
            }

            return View(potravinyDatabase);
        }

        // POST: PotravinyDatabase/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PotravinyDatabase == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PotravinyDatabase'  is null.");
            }
            var potravinyDatabase = await _context.PotravinyDatabase.FindAsync(id);
            if (potravinyDatabase != null)
            {
                _context.PotravinyDatabase.Remove(potravinyDatabase);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PotravinyDatabaseExists(int id)
        {
          return _context.PotravinyDatabase.Any(e => e.PotravinaDatabaseId == id);
        }
    }
}

PohybStrava/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PohybStrava.Data;
using PohybStrava.Models;

namespace PohybStrava.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public IActionResult Index()
        {
            var users = _context.User.Where(u => u.Email == this.User.Identity.Name || User.Identity.Name.Contains("admin"));

            return View(users);
        }

        // Users - mesicni prehledy
        public IActionResult PrumerUser()
        {
            var result =
                from s in _context.User
                group s by new { date = new DateTime(s.DatumUser.Year, s.DatumUser.Month, 1) } into g
                select new User
                {
                    DatumUser = g.Key.date,
                    VahaPrumer = Math.Round(g.Select(z => z.Vaha).Average(), 2),
                    BMIPrumer = Math.Round(g.Select(z => z.BMI).Average(), 2)
                };

            return View(result);
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,DatumUser,Jmeno,Prijmeni,Email,Pohlavi,Vek,Vaha,Vyska")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var name = this.User.Identity.Name;

            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,DatumUser,Jmeno,Prijmeni,Email,Pohlavi,Vek,Vaha,Vyska")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.User == null)
            {
                return Problem("Entity set 'ApplicationDbContext.User'  is null.");
            }
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return _context.User.Any(e => e.UserId == id);
        }
    }
}

PohybStrava/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="author" content="Pavel Rössner" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/lightbox2/css/lightbox.min.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />

</head>
<body>
    <header class="container-fluid">
        <div class="row">
            <div class="col d-flex align-items-center justify-content-end">

                <nav class="navbar navbar-expand-lg navbar-dark py-0">

                    <button class="navbar-toggler my-3 responzivnitlacitko" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse text-nowrap" id="navbarSupportedContent">

                        <ul class="navbar-nav mr-auto d-flex align-items-center">

                            <li class="nav-item navbar-underline"><a asp-controller="Home" asp-action="Index" id="barva">Úvod</a></li>

                            <li class="nav-item dropdown">
                                <div class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="barva">
                                    Sportovec
                                </div>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="Index" id="barva">Denní hodnoty</a>
                                    <a class="dropdown-item" asp-controller="Users" asp-action="PrumerUser" id="barva">Měsíční průměry</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <div class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="barva">
                                    Strava
                                </div>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Diets" asp-action="Index" id="barva">Denní hodnoty</a>
                                    <a class="dropdown-item" asp-controller="Diets" asp-action="SoucetDietsDen" id="barva">Denní součty</a>
                                    <a class="dropdown-item" asp-controller="Diets" asp-action="PrehledMesic" id="barva">Měsíční přehledy</a>
                                    <a class="dropdown-item" asp-controller="PotravinyDatabase" asp-action="Index" id="barva">Databáze potravin</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <div class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="barva">
                                    Sportovní aktivity
                                </div>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Activities" asp-action="Index" id="barva">Denní hodnoty</a>
                                    <a class="dropdown-item" asp-controller="Activities" asp-action="SoucetActivitiesDen" id="barva">Denní součty</a>
                                    <a class="dropdown-item" asp-controller="Activities" asp-action="PrehledMesic" id="barva">Měsíční přehledy</a>
                                </div>
                            </li>
                            <li class="nav-item navbar-underline"><a asp-controller="PrijemVydejEnergie" asp-action="Index" id="barva">Energetická bilance</a></li>
                            <li class="nav-item dropdown">
                                <div class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="barva">
                                    Přihlášení/registrace
                                </div>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Login" id="barva">Přihlášení</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout" id="barva">Odhlášení</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Register" id="barva">Registrovat</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Administration" id="barva">Administrace</a>
                                </div>
                            </li>
                            <li class="nav-item" id="barva">
                                <a href="/Account/Administration">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a>Přihlášen jako: </a>
                                        <span> @User.Identity.Name </span>
                                    }
                                </a>
                            </li>
                            <li class="nav-item px-2 navbar-underline"><a asp-controller="Home" asp-action="About" id="barva">O aplikaci</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <article>

        @RenderBody()

    </article>

    @if (ViewData["Title"] != "Kontakt")

    {
        <footer>
            Vytvořil &copy; Pavel Rössner @DateTime.Now.Year
            <a class="kontakt-tlacitko" asp-controller="Home" asp-action="Contact">Kontakt</a>
        </footer>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/css/bootstrap.css"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/lightbox2/js/lightbox.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>